import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { plusJakarta } from "./fonts";
import "./globals.css";
import Navbar from "../../components/Navbar";
import Footer from "../../components/Footer";


export const metadata: Metadata = {
  title: "My Brand Labs",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <style>
        {`
        
        body {
          font-family: ${plusJakarta.style.fontFamily}, sans-serif;
          
        }


         h1, h2, h3, h4, h5, h6 {
          font-family: ${plusJakarta.style.fontFamily}, sans-serif;
          font-weight: 700;
        }
        `}
        </style>
      </head>
      <body
        className={`${plusJakarta.className} antialiased`} 
      >
        <div className='fixed inset-0 bg-[url("/images/backgroundTexture.png")] bg-cover bg-center opacity-[6%] pointer-events-none z-0' />

        <Navbar />
        {children}
        <Footer/>
      </body>
    </html>
  );
}
